### PR TITLE
Change behaviour of sendfile(2) on FreeBSD to mimic Linux

### PR DESCRIPTION
**Pull request by shamazmazum**
Hi!

I think it would be a great idea to change `lfp_sendfile` on FreeBSD and derivatives so it returns number of bytes sent, not just 0 or -1. As manual says, this is exactly what Linux'es sendfile does.

Also I think there is no need to treat `EAGAIN` as an error because, unlike with `write` or `send`, it is an usual error code that `sendfile` returns even if a file is partially sent.

Finally, I remove obsolete `SF_MNOWAIT` flag.

### CODE REVIEW

**Comment by shamazmazum** [comment]
An excerpt from `sendfile(2)` manpage concerning `EAGAIN`

    [EAGAIN]
    The socket is marked for non-blocking I/O and not all data was sent due to the 
    socket buffer being filled.  If specified, the number of bytes successfully sent 
    will be returned in *sbytes

**Comment by shamazmazum** [comment]
Hi! I thought this project is dead, but got an email from github showing me it's not dead completely. Why this patch is without response for 2 years?

**Comment by sionescu** [comment]
Lack of time. I plan to go through the pull requests "soon".

**Comment by jmercouris** [comment]
@sionescu any update?

**Comment by shiorid** [comment]
@shamazmazum are you okay if I submit the patch to FreeBSD ports tree?

**Comment by shamazmazum** [comment]
@shiorid Sounds great!

**Comment by shamazmazum** [comment]
@sionescu Just checked, you actually closed my PR and pushed some shit which does not fix the problem. What's wrong with you? Spent some time to figure why my shitty HTML server does not work. Turns out my patch just disappeared.

@shiorid Are you a maintainer  of libfixposix in the ports tree? Can you push my version? Check the manual if in doubt.

**Comment by shamazmazum** [comment]
@sionescu  If you simply do not have time, I can be a maintainer. But just closing a PR and replacing a fix with something else is not OK.

**Comment by sionescu** [comment]
@shamazmazum If my change is faulty, please let me know why and I'll fix it.
And if you come here with this language again, you'll get banned.

**Comment by shiorid** [comment]
> @shiorid Are you a maintainer of libfixposix in the ports tree? Can you push my version? Check the manual if in doubt.

Yes, I'm the maintainer and will submit the changes to public review (since I'm not a committer).

Any way, I'm not a great C programmer, so could you confirm if the problem on the upstreamed _“fix”_ lives here?
```
if (res == 0) { return sbytes; }
    return res;
```

**Comment by shamazmazum** [comment]
> if my change is faulty, please let me know why and I'll fix it.

I wrote specially about `EAGAIN` case. I understand that not everyone can FreeBSD installed, so I copied that part of the manual for you. 

> And if you come here with this language again, you'll get banned.

This is your repository after all, you can do whatever you wish.

**Comment by shamazmazum** [comment]
@shiorid 

My original patch was:

~~~~
# elif defined(__FreeBSD__)
    return (ssize_t) sendfile(in_fd, out_fd, offset, nbytes, NULL, NULL, SF_MNOWAIT);
# elif defined(__FreeBSD__) || defined(__DragonFly__)
    off_t sbytes;
    int res = sendfile(in_fd, out_fd, offset, nbytes, NULL, &sbytes, 0);
    if (res == -1 && errno == EAGAIN)
        res = 0;
    if (res == 0) res = sbytes;
    return res;
~~~~

`EAGAIN` is not actually an error on FreeBSD. The number of bytes send will be present in `sbytes`.

**Comment by sionescu** [comment]
The usual semantics of EAGAIN is that no I/O was performed because the operation would have blocked. You mean that on FreeBSD that's not the case ?

**Comment by shamazmazum** [comment]
Exactly. See [here](https://www.freebsd.org/cgi/man.cgi?query=sendfile&sektion=2) or in my second comment

**Comment by shiorid** [comment]
>EAGAIN is not actually an error on FreeBSD. The number of bytes send will be present in sbytes.

@shamazmazum thank you for the explanation.

Since 0.5.0 is not yet released, I'll cherry-pick your fix and bump the revision in ports tree.

Thank you for letting me know.

**Comment by sionescu** [comment]
I've committed cc5063455184.

**Comment by shamazmazum** [comment]
Thanks. I can confirm that it works now.

**Comment by shamazmazum** [comment]
Not if I was interested, but are you sure that `__APPLE__` has the same behaviour?

**Comment by sionescu** [comment]
The [official man page](https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man2/sendfile.2.html) says so:

``
When using a socket marked for non-blocking I/O, sendfile() may send
fewer bytes than requested.  In this case, the number of bytes success-fully successfully
fully sent is returned in the via the len parameters and the error EAGAIN
is returned.
``

**Comment by shamazmazum** [comment]
Oh, OK. Thanks

**Comment by shamazmazum** [comment]
BTW, you did it incorrect again. Look at my patch:

~~~~
int res = sendfile(in_fd, out_fd, offset, nbytes, NULL, &sbytes, 0);
    if (res == -1 && errno == EAGAIN)
        res = 0;
    if (res == 0) res = sbytes;
    return res;
~~~~

and at what you did:

~~~~
    off_t sbytes = 0;
    int res = sendfile(in_fd, out_fd, offset, nbytes, NULL, &sbytes, 0);
    if (res == 0 || (res < 0 && errno == EAGAIN && sbytes > 0)) {
        return sbytes;
    }
    return -1;
~~~~

Don't you see a corner case? Hint: look what happens when `sbytes == 0`. I really cannot understand why you continue to ignore a correct patch and write your own "fixes" (this will be third) instead. You just got offended when I asked the first time.

**Comment by sionescu** [comment]
The purpose of lfp_sendfile() is to emulate the semantics of the Linux sendfile(), which are as follows:

* if zero bytes were written, it returns an error and sets errno to EAGAIN
* otherwise, the number of written bytes is returned, and a short write is detected by comparing the return value with the requested number of bytes

In other words, the current treatment of EAGAIN with sbytes==0 is correct, and it's what I meant. Your patch was incorrect.

**Comment by shamazmazum** [comment]
OK, I am wrong, sorry. It wasn't clear for me what is considered a successful transfer on Linux (see  [here](https://man7.org/linux/man-pages/man2/sendfile.2.html)):

~~~~
  If the transfer was successful, the number of bytes written to
       out_fd is returned.  Note that a successful call to sendfile()
       may write fewer bytes than requested; the caller should be
       prepared to retry the call if there were unsent bytes.  See also
       NOTES.

       On error, -1 is returned, and errno is set to indicate the error.
~~~~

I thought transfering zero bytes can also be considered successful (it's not clear then, in what cases `EAGAIN` should be returned as an error). It seems that returning zero has a different semantics on Linux and FreeBSD ([here](https://stackoverflow.com/questions/3697002/with-sendfile-is-it-possible-to-tell-when-in-fd-is-at-eof) is a discussion). My original intent was to mask `EAGAIN` because on FreeBSD it's not an error, actually. But I see I am wrong and on Linux returning zero and returning `-1`+`EAGAIN` are different things.

**Comment by shiorid** [comment]
hey, just to make you know, the fix [is on ports tree.](https://cgit.freebsd.org/ports/commit/?id=2c0c288cb09231ccdfd7ec6f3616121c923d51ad)

Cheers!

**Comment by sionescu** [comment]
@shamazmazum a return of 0 means EOF.

**Pull request closed without merging**
